[package]
name = "repl"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
monkey-core = { path = "../monkey-core/" }
termcolor = { version = "1.4.*" }

[dev-dependencies]
assert_cmd = "2.0.16"
